// Mocks generated by Mockito 5.4.6 from annotations
// in fixit_now/test/presentation/providers/profile_and_settings_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fixit_now/core/services/user_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i2.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i4.Future<List<dynamic>> getRequesters() => (super.noSuchMethod(
        Invocation.method(
          #getRequesters,
          [],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<List<dynamic>> searchRequesterByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRequesterByName,
          [name],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createRequester(
          Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRequester,
          [userData],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updateRequester(
    int? id,
    Map<String, dynamic>? userData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRequester,
          [
            id,
            userData,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> deleteRequester(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRequester,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updateProfile({
    required int? userId,
    String? name,
    String? email,
    String? phone,
    String? gender,
    String? cbeAccount,
    String? paypalAccount,
    String? telebirrAccount,
    String? awashAccount,
    String? serviceType,
    String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #userId: userId,
            #name: name,
            #email: email,
            #phone: phone,
            #gender: gender,
            #cbeAccount: cbeAccount,
            #paypalAccount: paypalAccount,
            #telebirrAccount: telebirrAccount,
            #awashAccount: awashAccount,
            #serviceType: serviceType,
            #password: password,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<dynamic>> getProviders() => (super.noSuchMethod(
        Invocation.method(
          #getProviders,
          [],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<List<dynamic>> searchProviderByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProviderByName,
          [name],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createProvider(
          Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProvider,
          [userData],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updateProvider(
    int? id,
    Map<String, dynamic>? userData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProvider,
          [
            id,
            userData,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> deleteProvider(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProvider,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<dynamic>> getTopRatedProviders() => (super.noSuchMethod(
        Invocation.method(
          #getTopRatedProviders,
          [],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<int> getTotalProviders() => (super.noSuchMethod(
        Invocation.method(
          #getTotalProviders,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}
